"use client"

import { useState, useEffect } from "react"
import Link from "next/link"
import { useRouter, useParams } from "next/navigation"
import { motion, AnimatePresence } from "framer-motion"
import { ArrowLeft, Download, X, Zap } from "lucide-react"
import Header from "@/app/components/Header"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"

interface TestResult {
  id: string
  testName: string
  status: string
  duration: number
  error?: string
  screenshot?: string
}

interface TestBug {
  id: string
  testName: string
  title: string
  severity: string
  category: string
  steps: string
  expected: string
  actual: string
  screenshot?: string
  aiAnalysis: string
  suggestion: string
}

interface TestRun {
  id: string
  platformUrl: string
  status: string
  totalTests: number
  passed: number
  failed: number
  duration?: number
  summary?: string
  createdAt: string
}

const severityColors: Record<string, { bg: string; text: string }> = {
  P0: { bg: "bg-red-50", text: "text-red-600" },
  P1: { bg: "bg-orange-50", text: "text-orange-600" },
  P2: { bg: "bg-yellow-50", text: "text-yellow-600" },
  P3: { bg: "bg-blue-50", text: "text-blue-600" },
  P4: { bg: "bg-gray-50", text: "text-gray-600" },
}

export default function TestRunPage() {
  const params = useParams()
  const runId = params.runId as string

  const [run, setRun] = useState<TestRun | null>(null)
  const [results, setResults] = useState<TestResult[]>([])
  const [bugs, setBugs] = useState<TestBug[]>([])
  const [selectedBug, setSelectedBug] = useState<TestBug | null>(null)
  const [loading, setLoading] = useState(true)
  const [currentTest, setCurrentTest] = useState<string | null>(null)
  const [progress, setProgress] = useState({ current: 0, total: 0 })
  const [liveLog, setLiveLog] = useState<{ name: string; status: "running" | "passed" | "failed" }[]>([])
  const [stepLog, setStepLog] = useState<{ step: string; status: "running" | "done" | "error" }[]>([])

  useEffect(() => {
    // Fetch initial data
    fetchRunData()

    // Connect SSE
    const es = new EventSource(`/api/test/${runId}/stream`)

    es.onmessage = (e) => {
      const event = JSON.parse(e.data)

      switch (event.type) {
        case "test_start":
          setCurrentTest(event.testName)
          setProgress({ current: event.index + 1, total: event.total })
          setLiveLog(prev => [...prev, { name: event.testName, status: "running" }])
          break

        case "test_pass":
          setLiveLog(prev => prev.map(t => t.name === event.testName ? { ...t, status: "passed" } : t))
          setTimeout(() => fetchRunData(), 500)
          break

        case "test_fail":
          setLiveLog(prev => prev.map(t => t.name === event.testName ? { ...t, status: "failed" } : t))
          setTimeout(() => fetchRunData(), 500)
          break

        case "step_update":
          setStepLog(prev => {
            const last = prev[prev.length - 1]
            if (last?.step === event.step && last.status === "running") {
              return [...prev.slice(0, -1), { step: event.step, status: event.status }]
            }
            return [...prev, { step: event.step, status: event.status }]
          })
          break

        case "run_complete":
          setCurrentTest(null)
          fetchRunData()
          es.close()
          break

        case "run_error":
          console.error("Test error:", event.error)
          es.close()
          break
      }
    }

    return () => es.close()
  }, [runId])

  async function fetchRunData() {
    try {
      const res = await fetch(`/api/test/${runId}`)
      const data = await res.json()
      setRun(data.run)
      setResults(data.run.results || [])
      setBugs(data.run.bugs || [])
      setLoading(false)
    } catch (err) {
      console.error("Error fetching run data:", err)
    }
  }

  function exportReport() {
    if (!run) return

    const md = `# Test Report: ${run.platformUrl}

Generated: ${new Date().toLocaleString()}

## Summary
- **Total Tests:** ${run.totalTests}
- **Passed:** ${run.passed}
- **Failed:** ${run.failed}
- **Pass Rate:** ${run.totalTests > 0 ? Math.round((run.passed / run.totalTests) * 100) : 0}%
- **Duration:** ${run.duration || 0}s

${run.summary ? `**AI Summary:** ${run.summary}\n` : ""}

## Bugs Found (${bugs.length})

${bugs.map((bug) => `### ${bug.severity} - ${bug.title}
**Test:** ${bug.testName}
**Category:** ${bug.category}

**Root Cause:**
${bug.aiAnalysis}

**Reproduction Steps:**
${JSON.parse(bug.steps).map((s: string, i: number) => `${i + 1}. ${s}`).join("\n")}

**Expected:** ${bug.expected}
**Actual:** ${bug.actual}

**Fix Suggestion:**
${bug.suggestion}

---

`).join("\n")}

---
Generated by AI Test Agent
`

    const blob = new Blob([md], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `test-report-${runId}.md`
    a.click()
  }

  if (loading && !run) {
    return (
      <div className="min-h-screen bg-[#f3f4f6] flex items-center justify-center">
        <div className="text-center">
          <div className="w-12 h-12 rounded-full border-4 border-gray-200 animate-spin mx-auto mb-4" style={{ borderTopColor: "#0891b2" }}></div>
          <p className="text-gray-600">Loading test run...</p>
        </div>
      </div>
    )
  }

  if (!run) {
    return (
      <div className="min-h-screen bg-[#f3f4f6] flex items-center justify-center">
        <p className="text-gray-600">Test run not found</p>
      </div>
    )
  }

  const passRate = run.totalTests > 0 ? Math.round((run.passed / run.totalTests) * 100) : 0

  return (
    <div className="min-h-screen bg-[#f3f4f6]">
      <Header />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-8">
        {/* Header */}
        <motion.div initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} className="mb-6">
          <Link href="/test" className="text-[#7a8899] hover:text-[#dc2626] text-sm mb-4 inline-flex items-center gap-1">
            <ArrowLeft className="h-4 w-4" /> Back to Runs
          </Link>
          <div className="flex items-start justify-between gap-4">
            <div>
              <h1 className="text-base font-medium text-gray-700">
                {(() => { try { return new URL(run.platformUrl).hostname.replace(/^www\./, "") } catch { return run.platformUrl } })()}
              </h1>
              <p className="text-sm text-gray-500 mt-1">{new Date(run.createdAt).toLocaleString()}</p>
            </div>
            <div className="flex gap-2">
              <Button onClick={exportReport} variant="outline" className="rounded-lg border-gray-300">
                <Download className="h-4 w-4 mr-2" />
                Export Report
              </Button>
            </div>
          </div>
        </motion.div>

        {/* Live Progress Panel */}
        {(run.status === "running" || run.status === "pending" || liveLog.length > 0) && (
          <motion.div
            className="mb-6 bg-white border border-[#e8edf5] rounded-xl shadow-sm overflow-hidden"
            initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}
          >
            {/* Header */}
            <div className="px-5 py-3.5 border-b border-[#f0f2f5] flex items-center justify-between" style={{ background: "#ecfeff" }}>
              <div className="flex items-center gap-2.5">
                {run.status === "running" || run.status === "pending" ? (
                  <>
                    <span className="relative flex h-2.5 w-2.5">
                      <span className="animate-ping absolute inline-flex h-full w-full rounded-full opacity-75" style={{ background: "#0891b2" }} />
                      <span className="relative inline-flex rounded-full h-2.5 w-2.5" style={{ background: "#0891b2" }} />
                    </span>
                    <span className="text-sm font-semibold" style={{ color: "#0891b2" }}>Live</span>
                  </>
                ) : (
                  <span className="text-sm font-semibold text-green-600">Completed</span>
                )}
                {progress.total > 0 && (
                  <span className="text-xs text-gray-500">{progress.current}/{progress.total} tests</span>
                )}
              </div>
              {currentTest && (
                <div className="flex items-center gap-2">
                  <div className="w-3.5 h-3.5 rounded-full border-2 border-gray-200 animate-spin" style={{ borderTopColor: "#0891b2" }} />
                  <span className="text-xs text-gray-600 max-w-xs truncate">
                    Running: <span className="font-medium text-gray-900">{currentTest}</span>
                  </span>
                </div>
              )}
            </div>

            {/* Progress bar */}
            {progress.total > 0 && (
              <div className="h-1 w-full bg-gray-100">
                <div
                  className="h-1 transition-all duration-500"
                  style={{ width: `${(progress.current / progress.total) * 100}%`, background: "#0891b2" }}
                />
              </div>
            )}

            {/* Live log */}
            {liveLog.length > 0 && (
              <div className="divide-y divide-[#f0f2f5] max-h-48 overflow-y-auto scrollbar-hide">
                {liveLog.map((t, i) => (
                  <div key={i} className="px-5 py-2.5 flex items-center gap-3">
                    {t.status === "running" ? (
                      <div className="w-3.5 h-3.5 rounded-full border-2 border-gray-200 animate-spin flex-shrink-0" style={{ borderTopColor: "#0891b2" }} />
                    ) : t.status === "passed" ? (
                      <span className="text-green-500 text-sm flex-shrink-0">✅</span>
                    ) : (
                      <span className="text-red-500 text-sm flex-shrink-0">❌</span>
                    )}
                    <span className={`text-sm truncate ${t.status === "running" ? "text-gray-700 font-medium" : "text-gray-600"}`}>
                      {t.name}
                    </span>
                    <span className="ml-auto text-xs flex-shrink-0" style={
                      t.status === "running" ? { color: "#0891b2" } :
                      t.status === "passed" ? { color: "#16a34a" } : { color: "#dc2626" }
                    }>
                      {t.status === "running" ? "running..." : t.status}
                    </span>
                  </div>
                ))}
              </div>
            )}

            {liveLog.length === 0 && (run.status === "running" || run.status === "pending") && (
              <div className="px-5 py-4 text-sm text-gray-400 flex items-center gap-2">
                <div className="w-3.5 h-3.5 rounded-full border-2 border-gray-200 animate-spin" style={{ borderTopColor: "#0891b2" }} />
                Preparing test suite...
              </div>
            )}

            {/* Live step log */}
            {stepLog.length > 0 && (
              <div className="border-t border-[#f0f2f5]">
                <div className="px-5 py-2 bg-gray-50 border-b border-[#f0f2f5]">
                  <p className="text-xs font-semibold text-gray-400 uppercase tracking-wider">Steps</p>
                </div>
                <div className="max-h-48 overflow-y-auto scrollbar-hide divide-y divide-[#f5f5f5]">
                  {stepLog.map((s, i) => (
                    <div key={i} className="px-5 py-2 flex items-center gap-3">
                      {s.status === "running" ? (
                        <div className="w-3 h-3 rounded-full border-2 border-gray-200 animate-spin flex-shrink-0" style={{ borderTopColor: "#0891b2" }} />
                      ) : s.status === "done" ? (
                        <span className="text-green-500 text-xs flex-shrink-0">✓</span>
                      ) : (
                        <span className="text-red-500 text-xs flex-shrink-0">✗</span>
                      )}
                      <span className={`text-xs truncate ${
                        s.status === "running" ? "text-gray-800 font-medium" :
                        s.status === "error" ? "text-red-500" : "text-gray-400"
                      }`}>{s.step}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </motion.div>
        )}

        {/* Summary Cards */}
        <motion.div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {[
            { label: "Pass Rate", value: `${passRate}%`, color: "text-green-600" },
            { label: "Passed", value: run.passed, color: "text-green-600" },
            { label: "Failed", value: run.failed, color: "text-red-600" },
            { label: "Bugs", value: bugs.length, color: "text-orange-600" },
          ].map((stat) => (
            <div key={stat.label} className="bg-white border border-[#e8edf5] rounded-xl px-4 py-3 shadow-sm">
              <p className="text-xs text-gray-600 mb-1">{stat.label}</p>
              <p className={`text-2xl font-bold ${stat.color}`}>{stat.value}</p>
            </div>
          ))}
        </motion.div>

        {/* Layout: Left (Results) + Right (Bugs) */}
        <motion.div className="grid grid-cols-1 lg:grid-cols-3 gap-6" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          {/* Left: Test Results */}
          <div className="lg:col-span-1 bg-white border border-[#e8edf5] rounded-xl shadow-sm overflow-hidden">
            <div className="px-5 py-4 border-b border-[#f0f2f5] bg-gray-50">
              <h3 className="font-semibold text-gray-900 text-sm">Test Results ({results.length})</h3>
            </div>
            <div className="max-h-96 overflow-y-auto scrollbar-hide">
              {results.map((result) => (
                <div key={result.id} className="px-5 py-3 border-b border-[#f0f2f5] last:border-b-0 hover:bg-gray-50 transition-colors">
                  <div className="flex items-center gap-2 mb-1">
                    {result.status === "passed" ? (
                      <span className="text-green-600 text-lg">✅</span>
                    ) : (
                      <span className="text-red-600 text-lg">❌</span>
                    )}
                    <p className="font-medium text-sm text-gray-900 flex-1 break-words">{result.testName}</p>
                  </div>
                  <p className="text-xs text-gray-500">{result.duration}ms</p>
                </div>
              ))}
            </div>
          </div>

          {/* Right: Bugs */}
          <div className="lg:col-span-2 bg-white border border-[#e8edf5] rounded-xl shadow-sm overflow-hidden">
            <div className="px-5 py-4 border-b border-[#f0f2f5] bg-gray-50">
              <h3 className="font-semibold text-gray-900 text-sm">Bugs Found ({bugs.length})</h3>
            </div>
            <div className="max-h-96 overflow-y-auto scrollbar-hide">
              {bugs.length === 0 ? (
                <div className="px-5 py-8 text-center text-gray-500">
                  <Zap className="h-12 w-12 mx-auto mb-2 text-gray-300" />
                  All tests passed! No bugs found.
                </div>
              ) : (
                bugs.map((bug) => (
                  <button
                    key={bug.id}
                    onClick={() => setSelectedBug(bug)}
                    className="w-full px-5 py-3 border-b border-[#f0f2f5] last:border-b-0 text-left hover:bg-gray-50 transition-colors"
                  >
                    <div className="flex items-start gap-3">
                      <Badge
                        variant="outline"
                        className={`flex-shrink-0 ${severityColors[bug.severity].bg} ${severityColors[bug.severity].text} border-0`}
                      >
                        {bug.severity}
                      </Badge>
                      <div className="flex-1 min-w-0">
                        <p className="font-medium text-sm text-gray-900 truncate">{bug.title}</p>
                        <p className="text-xs text-gray-500 mt-1">{bug.testName}</p>
                      </div>
                    </div>
                  </button>
                ))
              )}
            </div>
          </div>
        </motion.div>
      </div>

      {/* Bug Detail Modal */}
      <AnimatePresence>
        {selectedBug && (
          <>
            <motion.div className="fixed inset-0 bg-black/30 backdrop-blur-sm z-40" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelectedBug(null)} />
            <motion.div className="fixed right-0 top-0 h-full w-full max-w-2xl bg-white shadow-2xl z-50 overflow-y-auto scrollbar-hide" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }}>
              <div className="sticky top-0 bg-white border-b border-[#e8edf5] px-6 py-4 flex items-center justify-between">
                <h2 className="font-semibold text-gray-900">Bug Details</h2>
                <button onClick={() => setSelectedBug(null)} className="text-gray-400 hover:text-gray-600">
                  <X className="h-5 w-5" />
                </button>
              </div>

              <div className="p-6 space-y-6">
                {/* Title & Severity */}
                <div>
                  <div className="flex items-start gap-3 mb-2">
                    <Badge className={`${severityColors[selectedBug.severity].bg} ${severityColors[selectedBug.severity].text} border-0`}>
                      {selectedBug.severity}
                    </Badge>
                    <Badge variant="outline" className="bg-gray-50 text-gray-600 border-gray-200">
                      {selectedBug.category}
                    </Badge>
                  </div>
                  <h3 className="text-lg font-bold text-gray-900">{selectedBug.title}</h3>
                  <p className="text-sm text-gray-600 mt-1">Test: {selectedBug.testName}</p>
                </div>

                {/* Screenshot */}
                {selectedBug.screenshot && (
                  <div>
                    <p className="text-sm font-semibold text-gray-900 mb-2">Screenshot</p>
                    <img src={`data:image/png;base64,${selectedBug.screenshot}`} alt="Failure screenshot" className="w-full rounded-lg border border-gray-200" />
                  </div>
                )}

                {/* Reproduction Steps */}
                <div>
                  <p className="text-sm font-semibold text-gray-900 mb-2">Reproduction Steps</p>
                  <ol className="space-y-1 text-sm text-gray-700 list-decimal list-inside">
                    {JSON.parse(selectedBug.steps).map((step: string, i: number) => (
                      <li key={i}>{step}</li>
                    ))}
                  </ol>
                </div>

                {/* Expected vs Actual */}
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-sm font-semibold text-gray-900 mb-2">Expected</p>
                    <p className="text-sm text-gray-700 bg-green-50 border border-green-200 rounded-lg p-3">{selectedBug.expected}</p>
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-gray-900 mb-2">Actual</p>
                    <p className="text-sm text-gray-700 bg-red-50 border border-red-200 rounded-lg p-3">{selectedBug.actual}</p>
                  </div>
                </div>

                {/* AI Analysis */}
                <div>
                  <p className="text-sm font-semibold text-gray-900 mb-2">AI Root Cause Analysis</p>
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-sm text-blue-900">{selectedBug.aiAnalysis}</div>
                </div>

                {/* Fix Suggestion */}
                <div>
                  <p className="text-sm font-semibold text-gray-900 mb-2">Fix Suggestion</p>
                  <div className="bg-green-50 border border-green-200 rounded-lg p-4 text-sm text-green-900">{selectedBug.suggestion}</div>
                </div>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  )
}
